# Generated by Django 5.2.12 on 2026-03-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("DIRECT_INFERENCE", "Direktes Schließen"),
                            ("CASE_SPLIT", "Fallunterscheidung"),
                        ],
                        max_length=20,
                    ),
                ),
                ("level", models.IntegerField()),
                ("premises", models.JSONField()),
                ("premises_sympy", models.JSONField()),
                ("variables", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
