# Generated by Django 5.2.11 on 2026-02-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generate_tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="premises_sympy",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
