# Generated by Django 5.2.12 on 2026-03-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generate_tasks", "0002_alter_task_task_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("DIRECT_INFERENCE", "Direktes Schließen"),
                    ("CASE_SPLIT", "Fallunterscheidung"),
                ],
                max_length=20,
            ),
        ),
    ]
