# Generated by Django 5.2.11 on 2026-02-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generate_tasks", "0002_task_premises_sympy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="premises_sympy",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
