# Generated by Django 5.2.11 on 2026-02-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeedbackRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("DIRECT_INFERENCE", "Direct inference"),
                            ("CASE_SPLIT", "Case split"),
                        ],
                        max_length=30,
                    ),
                ),
                ("min_level", models.IntegerField(default=1)),
                ("max_level", models.IntegerField(default=4)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Feedback-Regel",
                "verbose_name_plural": "Feedback-Regeln",
            },
        ),
    ]
