# Generated by Django 5.2.11 on 2026-02-22 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FeedbackRule",
        ),
    ]
