# Generated by Django 5.2.12 on 2026-03-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprogress",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("CASE_SPLIT", "Fallunterscheidung"),
                    ("DIRECT_INFERENCE", "Direktes Schließen"),
                ],
                max_length=20,
            ),
        ),
    ]
