# Generated by Django 5.2.11 on 2026-02-18 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="correct_solved",
            field=models.IntegerField(
                default=0, help_text="Anzahl korrekt gelöster Aufgaben"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="highscore_streak",
            field=models.IntegerField(
                default=0, help_text="Höchste Streak aller Zeiten"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="total_solved",
            field=models.IntegerField(
                default=0, help_text="Gesamtzahl gelöster Aufgaben"
            ),
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("DIRECT_INFERENCE", "Unit Propagation"),
                            ("CASE_SPLIT", "Case Split"),
                        ],
                        max_length=20,
                    ),
                ),
                ("current_level", models.IntegerField(default=1)),
                (
                    "correct_in_row",
                    models.IntegerField(
                        default=0,
                        help_text="Anzahl korrekter Antworten in Folge im aktuellen Level",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False, help_text="Alle Levels abgeschlossen"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Nutzerfortschritt",
                "verbose_name_plural": "Nutzerfortschritte",
                "unique_together": {("user", "task_type")},
            },
        ),
    ]
