# Generated by Django 5.2.11 on 2026-02-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_correct_solved_user_highscore_streak_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_accessories",
            field=models.CharField(
                default="blank", help_text="Accessoires (Brille etc.)", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_clothing",
            field=models.CharField(
                default="blazerAndShirt", help_text="Kleidung", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_clothing_color",
            field=models.CharField(
                default="red", help_text="Kleidungsfarbe", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_eyebrows",
            field=models.CharField(
                default="default", help_text="Augenbrauen", max_length=30
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_eyes",
            field=models.CharField(default="default", help_text="Augen", max_length=30),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_facial_hair",
            field=models.CharField(default="blank", help_text="Bart", max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_hair_color",
            field=models.CharField(
                default="black", help_text="Haarfarbe", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_mouth",
            field=models.CharField(default="default", help_text="Mund", max_length=30),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_skin_color",
            field=models.CharField(
                default="light", help_text="Hautfarbe", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_top",
            field=models.CharField(
                default="shortHairShortFlat",
                help_text="Frisur/Kopfbedeckung",
                max_length=50,
            ),
        ),
    ]
