# Generated by Django 5.2.12 on 2026-03-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_userprogress_task_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprogress",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("CASE_SPLIT", "Fallunterscheidung"),
                    ("DIRECT_INFERENCE", "Direktes Schließen"),
                ],
                max_length=20,
            ),
        ),
    ]
