# Generated by Django 5.2.11 on 2026-02-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_avatar_accessories_user_avatar_clothing_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar_accessories",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Accessoires (Brille etc.)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar_clothing_color",
            field=models.CharField(
                default="e6544f", help_text="Kleidungsfarbe (Hex)", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar_facial_hair",
            field=models.CharField(
                blank=True, default="", help_text="Bart", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar_hair_color",
            field=models.CharField(
                default="2c1b18", help_text="Haarfarbe (Hex)", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar_skin_color",
            field=models.CharField(
                default="edb98a", help_text="Hautfarbe (Hex)", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar_top",
            field=models.CharField(
                default="shortFlat", help_text="Frisur/Kopfbedeckung", max_length=50
            ),
        ),
    ]
