# Generated by Django 5.2.11 on 2026-02-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_avatar_accessories_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="current_streak",
            field=models.IntegerField(
                default=0, help_text="Aktuelle Streak (seitenübergreifend)"
            ),
        ),
    ]
