# Generated by Django 5.2.12 on 2026-03-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_userprogress_task_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_facial_hair_color",
            field=models.CharField(
                default="", help_text="Bartfarbe (Hex)", max_length=20
            ),
        ),
    ]
