# Generated by Django 5.2.12 on 2026-03-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_avatar_facial_hair_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar_facial_hair_color",
            field=models.CharField(
                blank=True, default="", help_text="Bartfarbe (Hex)", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("DIRECT_INFERENCE", "Unit Propagation"),
                    ("CASE_SPLIT", "Case Split"),
                ],
                max_length=20,
            ),
        ),
    ]
