# Generated by Django 5.2.12 on 2026-03-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_userprogress_task_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprogress",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("DIRECT_INFERENCE", "Unit Propagation"),
                    ("CASE_SPLIT", "Case Split"),
                ],
                max_length=20,
            ),
        ),
    ]
