# Generated by Django 5.2.11 on 2026-02-12 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SolutionCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.IntegerField(help_text="ID der Task")),
                (
                    "solver_name",
                    models.CharField(
                        help_text="z.B. 'marginal_solver'", max_length=100
                    ),
                ),
                ("result", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Solution Cache",
                "verbose_name_plural": "Solution Caches",
                "indexes": [
                    models.Index(
                        fields=["task_id", "solver_name"],
                        name="solve_tasks_task_id_2b3999_idx",
                    )
                ],
            },
        ),
    ]
